config/routes.rb
Scorepad::Application.routes.draw do

  get "page/index"
  get "page/contact"

  resources :users do
    resources :games
  end

  root :to => 'page#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessible :type_of
  belongs_to :user
  has_many :players, :dependent => :destroy
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :user
  belongs_to :game
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :facebook_id, :phone_id, :guid, :device_name, :device_platform, :device_version
  has_many :games, :dependent => :destroy
  validates_uniqueness_of :email

  # INCLUDE THE UDID -> USER DEVICE ID TO HELP SECURITY
  # USER ID FOR CREATING ACCOUNTS???
  # INCLUDE A PRIVATE KEY THAT IS INCLUDED IN THE APP
  # HELPS SANITY CHECK ITS REAL
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def pubnub
    @pubnub ||= Pubnub.new(
      'pub-c82313ac-0539-4360-a94a-ca61815162e1',
      'sub-8f210f63-de68-11e0-87ea-fd1c1c3f5d78',
      "",      ## SECRET_KEY
      false    ## SSL_ON?
    )

  end

  def publish(options={})
    o = {:channel => 'hello_world', :message => 'sup??'}.merge(options)
    info = pubnub.publish({
      'channel' => o[:channel],
      'message' => o[:message]
    })

    if info[0]==0  #FAILED PUBLISH
      print info[1]
    end

  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  # GET /games
  # GET /games.json
  def index
    @user = User.find(params[:user_id])
    @games = @user.games.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @games }
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @user = User.find(params[:user_id])    
    @game = @user.games.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @game }
    end
  end

  # GET /games/new
  # GET /games/new.json
  def new
    @user = User.find(params[:user_id])
    @game = @user.games.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @game }
    end
  end

  # GET /games/1/edit
  def edit
    @user = User.find(params[:user_id])
    @game = @user.games.find(params[:id])
  end

  # POST /games
  # POST /games.json
  def create
    @user = User.find(params[:user_id])
    @game = @user.games.new(params[:game])

    respond_to do |format|
      if @game.save
        format.html { redirect_to user_game_path(@user,@game), :notice => 'Game was successfully created.' }
        format.json { render :json => @game, :status => :created }
      else
        format.html { render :action => "new" }
        format.json { render :json => @game.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /games/1
  # PUT /games/1.json
  def update
    @user = User.find(params[:user_id])
    @game = @user.games.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(params[:game])
        format.html { redirect_to user_game_path(@user,@game), :notice => 'Game was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @game.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @user = User.find(params[:user_id])
    @game = @user.games.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to user_games_url(@user) }
      format.json { head :ok }
    end
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
    #publish(:channel =>'hello_world', :message => 'texter')
  end

  def contact
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users, :callback => params[:callback] }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user, :callback => params[:callback] }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, :notice => 'User was successfully created.' }
        format.json { render :json => @user, :status => :created }
      else
        format.html { render :action => "new" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, :notice => 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/_form.html.erb
<%= form_for([@user,@game]) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br />
    <%= select("game", "user_id", User.all.collect {|u| [ u.email, u.id] } ) %>
  </div>
  <div class="field">
    <%= f.label :type_of %><br />
    <%= f.text_field :type_of %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', user_game_path(@user,@game) %> |
<%= link_to 'Back', user_games_path(@user) %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<table>
  <tr>
    <th>User</th>
    <th>Type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @games.each do |game| %>
  <tr>
    <td><%= game.user.email %></td>
    <td><%= game.type_of %></td>
    <td><%= link_to 'Show', user_game_path(@user, game) %></td>
    <td><%= link_to 'Edit', edit_user_game_path(@user, game) %></td>
    <td><%= link_to 'Destroy', user_game_path(@user, game), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Create New Game', new_user_game_path(@user) %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', user_games_path(@user) %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @game.user.email %>
</p>

<p>
  <b>Type:</b>
  <%= @game.type_of %>
</p>


<%= link_to 'Edit', edit_user_game_path(@user,@game) %> |
<%= link_to 'Back', user_games_path(@user) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scorepad</title>
  <%= stylesheet_link_tag    "application" %>
  <%#= csrf_meta_tags %>
</head>
<body>

<%= yield %>
  <%= javascript_include_tag "application", "http://maccman.github.com/spine/spine.min.js" %>
  <div pub-key="pub-c82313ac-0539-4360-a94a-ca61815162e1" sub-key="sub-8f210f63-de68-11e0-87ea-fd1c1c3f5d78" ssl="off" origin="pubsub.pubnub.com" id="pubnub"></div>
  <script src="http://cdn.pubnub.com/pubnub-3.1.min.js"></script>

<%= yield :js %>

</body>
</html>

app/views/page/contact.html.erb
<h1>Page#contact</h1>
<p>Find me in app/views/page/contact.html.erb</p>

app/views/page/index.html.erb
<h1>Sup?</h1>


<% content_for :js do %>
<script>
  (function(){
    // LISTEN FOR MESSAGES
    PUBNUB.subscribe({
        channel  : "hello_world",      // CONNECT TO THIS CHANNEL.
        error    : function() {        // LOST CONNECTION (auto reconnects)
            alert("Connection Lost. Will auto-reconnect when Online.")
        },
        callback : function(message) { // RECEIVED A MESSAGE.
            alert(message)
        },
        connect  : function() {        // CONNECTION ESTABLISHED.

            // SEND MESSAGE
            //PUBNUB.publish({
            //    channel : "hello_world",
            //    message : "Hi from PubNub."
            //})

        }
    })

  })();
</script>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :facebook_id %><br />
    <%= f.text_field :facebook_id %>
  </div>
  <div class="field">
    <%= f.label :phone_id %><br />
    <%= f.text_field :phone_id %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Facebook</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.facebook_id %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Facebook:</b>
  <%= @user.facebook_id %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>